export { default as Team } from "./team/team";
export { default as Navbar } from './navbar/Navbar';
export { default as Detail } from './detail/detail';
export { default as Conn } from './cont/conn';
export { default as Time } from './events/event';
export { default as Party } from './events/conf';
export { default as PParty } from './events/confpointer';
export { default as Card } from './card/card';
export { default as Hero } from './Hero';